name: Deploy

on:
  push:
    branches:
      - 'gh-actions'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      # should build first and save the artifact
      - uses: actions/setup-node@v1
        with:
          node-version: '6.9.2'
      - name: build static assets 
        run: |
          pushd config/static-assets
          make clean
          make build
          popd
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: deploy static assets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          pushd config/static-assets/serverless
          npm install serverless
          npm install
          serverless deploy
          popd
      - name: deploy regualtions core API
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          pushd config/regulations-core
          npm install serverless
          npm install
          serverless deploy
          popd
      - name: deploy regualtions site server
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          pushd config/regulations-site
          npm install serverless
          npm install
          serverless deploy
          popd
